### ISSUE TITLE
git don`t update FrontEnd/src/app/config/settings.ts

### ISSUE THREAD

**Issue by moleisking** [moleisking/SAM#3]
error: Your local changes to the following files would be overwritten by merge:
	FrontEnd/src/app/config/settings.ts

**Comment by goodbytes23** [comment]
Did you make changes to it?

**Comment by moleisking** [comment]
Only to my android app. Not the backend.

**Comment by goodbytes23** [comment]
Its working fine here. I need more info about the issue.

**Comment by moleisking** [comment]
It works fine.  The problem is every install it tries to overwrite the same
settings when on the server.

**Comment by moleisking** [comment]
When installing on the server and doing a pull it complains about a Settings.ts file that was modified. This is because the Settings config file was changed for sendgrid. The push should ignore the uploading of  settings files to the repository.

**Comment by goodbytes23** [comment]
its added long ago.

https://github.com/moleisking/SAM/blob/master/.gitignore#L8
